version: '3'

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_USER: tradeplat4m
      POSTGRES_PASSWORD: Sd$$-3.16
      POSTGRES_DB: tradeplat4m 
    ports:
      - 5432:5432

  service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - timescale
    environment:
      CONFIG_PROFILE: local-docker
